version: '3.7'

services:
  api:
    container_name: petz
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://petz:docker@petz_db:5432/petz_db?schema=public
    deploy:
      replicas: 20
        update_config:
          parallelism: 5
          delay: 10s
        restart_policy:
          condition: on-failure
          max_attempts: 3
          window: 120s
    networks:
      - webnet
    depends_on:
      - petz_db

  petz_db:
    container_name: petz_db
    image: postgres:12
    environment:
      POSTGRES_DB: petz_db
      POSTGRES_USER: petz
      POSTGRES_PASSWORD: docker
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  pgdata:
